version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/pyoptional"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
