name: Upload Python Package

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Poetry
      uses: snok/install-poetry@v1.3
      with:
        version: 1.4.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Build and publish
      run: |
        poetry build -vvv
        poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
